# Generated by Django 5.0.3 on 2024-03-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_website', models.URLField(blank=True)),
                ('designation', models.CharField(choices=[('hr', 'HR'), ('manager', 'Manager'), ('ceo', 'CEO')], default='hr', max_length=20)),
            ],
        ),
    ]
