# Generated by Django 5.0.3 on 2024-03-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0004_alter_job_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('work_from_home', 'Work From Home'), ('work_from_office', 'Work From Office'), ('hybrid', 'Hybrid')], max_length=20),
        ),
    ]
