# Generated by Django 5.0.3 on 2024-03-31 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0005_alter_job_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
