# Generated by Django 5.0.3 on 2024-03-31 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0007_job_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
