# Generated by Django 5.0.3 on 2024-04-01 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_alter_jobapplication_status'),
        ('users', '0005_alter_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='UserProfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
