# Generated by Django 5.0.3 on 2024-03-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='long_description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('office', 'Office'), ('home', 'Home'), ('hybrid', 'Hybrid')], default='office', max_length=10),
        ),
    ]
