# Generated by Django 5.0.3 on 2024-03-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_long_description1_job_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_size',
            field=models.CharField(choices=[('size_1-9', '1-3'), ('size_10-49', '3-6'), ('size_50-99', '6-10'), ('size_100', '10+')], default='size_1-9', max_length=20),
        ),
    ]
